#!/usr/bin/env python3
"""Fetch provisional rivers and streams from OpenStreetMap Overpass."""

from __future__ import annotations

import argparse
import json
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


OVERPASS_URL = "https://overpass-api.de/api/interpreter"
REPO_ROOT = Path(__file__).resolve().parents[1]
LOCAL_WATERWAYS_GPKG = REPO_ROOT / "Rios_filtrado_suavizado_optimizado.gpkg"


def read_bbox(metadata_path: Path) -> tuple[float, float, float, float]:
    metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
    west, south, east, north = metadata["map_bounds"]
    pad = 0.04
    return south - pad, west - pad, north + pad, east + pad


def overpass_query(bbox: tuple[float, float, float, float]) -> str:
    south, west, north, east = bbox
    return f"""
[out:json][timeout:90];
(
  way["waterway"~"^(river|stream|canal|drain|ditch)$"]({south},{west},{north},{east});
);
out tags geom;
"""


def fetch_json(query: str) -> dict[str, Any]:
    body = urllib.parse.urlencode({"data": query}).encode("utf-8")
    request = urllib.request.Request(
        OVERPASS_URL,
        data=body,
        headers={"User-Agent": "MapaInteractivo_Rios/0.1"},
    )
    with urllib.request.urlopen(request, timeout=120) as response:
        return json.loads(response.read().decode("utf-8"))


def to_geojson(payload: dict[str, Any]) -> dict[str, Any]:
    features = []
    for element in payload.get("elements", []):
        geometry = element.get("geometry") or []
        if len(geometry) < 2:
            continue
        tags = element.get("tags") or {}
        coords = [[point["lon"], point["lat"]] for point in geometry]
        features.append(
            {
                "type": "Feature",
                "properties": {
                    "osm_id": element.get("id"),
                    "name": tags.get("name") or tags.get("waterway") or "Sin nombre",
                    "waterway": tags.get("waterway"),
                    "source": "OpenStreetMap",
                    "generated_at": datetime.now(timezone.utc).isoformat(),
                },
                "geometry": {"type": "LineString", "coordinates": coords},
            }
        )
    features.sort(
        key=lambda feature: (
            feature["properties"].get("waterway") or "",
            feature["properties"].get("name") or "",
            feature["properties"].get("osm_id") or 0,
        )
    )
    return {"type": "FeatureCollection", "features": features}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--metadata",
        type=Path,
        default=Path("data/processed/metadata.json"),
        help="Metadata generated by export_base_layers.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("data/processed/waterways.geojson"),
    )
    parser.add_argument(
        "--force-osm",
        action="store_true",
        help="Replace the reviewed local hydrography with provisional OSM data.",
    )
    args = parser.parse_args()

    if LOCAL_WATERWAYS_GPKG.exists() and not args.force_osm:
        print(
            "No se descargo OSM: existe Rios_filtrado_suavizado_optimizado.gpkg. "
            "Use export_base_layers.py para regenerar la hidrografia local o "
            "--force-osm para reemplazarla de forma provisional."
        )
        return

    bbox = read_bbox(args.metadata)
    query = overpass_query(bbox)
    payload = fetch_json(query)
    geojson = to_geojson(payload)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(geojson, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    print(f"waterways: {len(geojson['features'])} features")


if __name__ == "__main__":
    main()
